Feature/result not found Block
web-slate/google-search-clone-web pull request #52
Opened 2022-03-13 01:06 UTC by sriramanvellingiri

#51

2022-03-13 03:03 UTC, ramsunvtech requested changes

2022-03-13 03:03 UTC, ramsunvtech commented on react/src/components/blocks/ResultNotFound/ResultNotFound.js
> +            <li> Make sure that all words are spelled correctly. </li>
localize this

2022-03-13 03:03 UTC, ramsunvtech commented on react/src/components/blocks/ResultNotFound/ResultNotFound.js
> +      <p>Your search -{props.searchText} - did not match any documents.</p>
destruct this like below

```
function ResultNotFound(props) {
const { searchText = '' } = props

  return (
    <>
      <p>Your search - {searchText} - did not match any documents.</p>
```

2022-03-13 03:03 UTC, ramsunvtech commented on react/src/components/blocks/ResultNotFound/ResultNotFound.js
> +        alt='ResultNotFound'
localize

2022-03-13 03:03 UTC, ramsunvtech commented on react/src/modules/SearchResults/SearchResults.js
> +import ResultNotFound from '@/blocks/ResultNotFound'
rename it as `NoResulFound`

2022-03-13 04:35 UTC, sriramanvellingiri commented on react/src/modules/SearchResults/SearchResults.js
> +import ResultNotFound from '@/blocks/ResultNotFound'
Done

2022-03-13 04:36 UTC, sriramanvellingiri commented on react/src/components/blocks/ResultNotFound/ResultNotFound.js
> +            <li> Make sure that all words are spelled correctly. </li>
Done

2022-03-14 00:57 UTC, ramsunvtech approved these changes

2022-03-14 00:59 UTC, merged